version: "3"

services:
    typesense:
        container_name: typesense-server
        image: typesense/typesense:0.24.0
        environment: # configure typesense server using environment variables
            TYPESENSE_DATA_DIR: /data
            TYPESENSE_ENABLE_CORS: true
            TYPESENSE_API_KEY: xyz
        ports:
            - 8108:8108
        volumes:
            - /typesense-data:/data # /typesense-data is used to store search engine data